{
Helysin = [
    { "ID": 1, "Ország": "Kína", "ÖkológiaiRégió": "Bambuszerdők" },
    { "ID": 2, "Ország": "Oroszország", "ÖkológiaiRégió": "Tajga erdők" },
    { "ID": 3, "Ország": "Ruanda", "ÖkológiaiRégió": "Hegyi esőerdők" },
    { "ID": 4, "Ország": "Csendes-óceán", "ÖkológiaiRégió": "Nyílt óceán" },
    { "ID": 5, "Ország": "USA", "ÖkológiaiRégió": "Erdők és mocsarak" },
    { "ID": 6, "Ország": "India", "ÖkológiaiRégió": "Mangrove erdők" },
    { "ID": 7, "Ország": "Ausztrália", "ÖkológiaiRégió": "Nagy Korallzátony" },
    { "ID": 8, "Ország": "Brazília", "ÖkológiaiRégió": "Amazon esőerdő" },
    { "ID": 9, "Ország": "Kenya", "ÖkológiaiRégió": "Szavanna" },
    { "ID": 10, "Ország": "Kanada", "ÖkológiaiRégió": "Boreális erdő" },
    { "ID": 11, "Ország": "Indonézia", "ÖkológiaiRégió": "Trópusi esőerdők" },
    { "ID": 12, "Ország": "Antarktisz", "ÖkológiaiRégió": "Jégtakarók" },
    { "ID": 13, "Ország": "Dél-Afrika", "ÖkológiaiRégió": "Fynbos" },
    { "ID": 14, "Ország": "Mexikó", "ÖkológiaiRégió": "Sivatagok és erdők" },
    { "ID": 15, "Ország": "Norvégia", "ÖkológiaiRégió": "Arktikus tajga" },
    { "ID": 16, "Ország": "Új-Zéland", "ÖkológiaiRégió": "Mérsékelt esőerdők" },
    { "ID": 17, "Ország": "Chile", "ÖkológiaiRégió": "Atacama sivatag" },
    { "ID": 18, "Ország": "Olaszország", "ÖkológiaiRégió": "Mediterrán cserjések" },
    { "ID": 19, "Ország": "Fülöp-szigetek", "ÖkológiaiRégió": "Korallzátonyok" },
    { "ID": 20, "Ország": "Peru", "ÖkológiaiRégió": "Felhőerdők" },
    { "ID": 21, "Ország": "Thaiföld", "ÖkológiaiRégió": "Örökzöld erdők" },
    { "ID": 22, "Ország": "Japán", "ÖkológiaiRégió": "Mérsékelt erdők" },
    { "ID": 23, "Ország": "Madagaszkár", "ÖkológiaiRégió": "Tüskés erdők" },
    { "ID": 24, "Ország": "Etiópia", "ÖkológiaiRégió": "Magasföldek" },
    { "ID": 25, "Ország": "Argentína", "ÖkológiaiRégió": "Patagóniai puszta" },
    { "ID": 26, "Ország": "Szaúd-Arábia", "ÖkológiaiRégió": "Sivatagok" },
    { "ID": 27, "Ország": "Alaszka", "ÖkológiaiRégió": "Tundra" },
    { "ID": 28, "Ország": "Németország", "ÖkológiaiRégió": "Vegyes erdők" },
    { "ID": 29, "Ország": "Vietnam", "ÖkológiaiRégió": "Mangrove mocsarak" },
    { "ID": 30, "Ország": "Franciaország", "ÖkológiaiRégió": "Lombhullató erdők" },
    { "ID": 31, "Ország": "Malajzia", "ÖkológiaiRégió": "Tőzeg mocsarak" },
    { "ID": 32, "Ország": "Kolumbia", "ÖkológiaiRégió": "Trópusi erdők" },
    { "ID": 33, "Ország": "Mianmar", "ÖkológiaiRégió": "Hegyi erdők" },
    { "ID": 34, "Ország": "Zimbabwé", "ÖkológiaiRégió": "Füves puszták" },
    { "ID": 35, "Ország": "Pakisztán", "ÖkológiaiRégió": "Thár sivatag" },
    { "ID": 36, "Ország": "Kongó", "ÖkológiaiRégió": "Alacsony esőerdők" },
    { "ID": 37, "Ország": "Tanzánia", "ÖkológiaiRégió": "Serengeti" },
    { "ID": 38, "Ország": "Irán", "ÖkológiaiRégió": "Zagros erdők" },
    { "ID": 39, "Ország": "Egyiptom", "ÖkológiaiRégió": "Nílus deltája" },
    { "ID": 40, "Ország": "Dél-Korea", "ÖkológiaiRégió": "Mérsékelt hegyek" },
    { "ID": 41, "Ország": "Marokkó", "ÖkológiaiRégió": "Atlasz-hegység" },
    { "ID": 42, "Ország": "Törökország", "ÖkológiaiRégió": "Sztyeppe és erdő" },
    { "ID": 43, "Ország": "Grönland", "ÖkológiaiRégió": "Jégtakarók" },
    { "ID": 44, "Ország": "Fidzsi", "ÖkológiaiRégió": "Trópusi szigetek" },
    { "ID": 45, "Ország": "Nepál", "ÖkológiaiRégió": "Himalája" },
    { "ID": 46, "Ország": "Bhután", "ÖkológiaiRégió": "Szubtrópusi erdők" },
    { "ID": 47, "Ország": "Venezuela", "ÖkológiaiRégió": "Orinoco medence" },
    { "ID": 48, "Ország": "Banglades", "ÖkológiaiRégió": "Sundarbans" },
    { "ID": 49, "Ország": "Kuba", "ÖkológiaiRégió": "Kubai szigetvilág" },
    { "ID": 50, "Ország": "Ukrajna", "ÖkológiaiRégió": "Sztyeppe és erdők" }
],
Meret = [
    { "ID": 1, "Hossz": 160, "Magasság": 90 },
    { "ID": 2, "Hossz": 300, "Magasság": 120 },
    { "ID": 3, "Hossz": 200, "Magasság": 180 },
    { "ID": 4, "Hossz": 250, "Magasság": 30 },
    { "ID": 5, "Hossz": 150, "Magasság": 70 },
    { "ID": 6, "Hossz": 180, "Magasság": 100 },
    { "ID": 7, "Hossz": 2500, "Magasság": 400 },
    { "ID": 8, "Hossz": 220, "Magasság": 120 },
    { "ID": 9, "Hossz": 200, "Magasság": 140 },
    { "ID": 10, "Hossz": 300, "Magasság": 130 },
    { "ID": 11, "Hossz": 400, "Magasság": 90 },
    { "ID": 12, "Hossz": 350, "Magasság": 60 },
    { "ID": 13, "Hossz": 180, "Magasság": 80 },
    { "ID": 14, "Hossz": 100, "Magasság": 50 },
    { "ID": 15, "Hossz": 250, "Magasság": 60 },
    { "ID": 16, "Hossz": 300, "Magasság": 130 },
    { "ID": 17, "Hossz": 250, "Magasság": 110 },
    { "ID": 18, "Hossz": 100, "Magasság": 60 },
    { "ID": 19, "Hossz": 150, "Magasság": 90 },
    { "ID": 20, "Hossz": 210, "Magasság": 100 },
    { "ID": 21, "Hossz": 250, "Magasság": 90 },
    { "ID": 22, "Hossz": 200, "Magasság": 150 },
    { "ID": 23, "Hossz": 250, "Magasság": 70 },
    { "ID": 24, "Hossz": 300, "Magasság": 130 },
    { "ID": 25, "Hossz": 500, "Magasság": 180 },
    { "ID": 26, "Hossz": 250, "Magasság": 100 },
    { "ID": 27, "Hossz": 180, "Magasság": 130 },
    { "ID": 28, "Hossz": 220, "Magasság": 150 },
    { "ID": 29, "Hossz": 150, "Magasság": 100 },
    { "ID": 30, "Hossz": 100, "Magasság": 60 },
    { "ID": 31, "Hossz": 200, "Magasság": 80 },
    { "ID": 32, "Hossz": 180, "Magasság": 120 },
    { "ID": 33, "Hossz": 170, "Magasság": 100 },
    { "ID": 34, "Hossz": 300, "Magasság": 110 },
    { "ID": 35, "Hossz": 100, "Magasság": 50 },
    { "ID": 36, "Hossz": 120, "Magasság": 60 },
    { "ID": 37, "Hossz": 200, "Magasság": 120 },
    { "ID": 38, "Hossz": 230, "Magasság": 80 },
    { "ID": 39, "Hossz": 300, "Magasság": 150 },
    { "ID": 40, "Hossz": 180, "Magasság": 100 },
    { "ID": 41, "Hossz": 250, "Magasság": 100 },
    { "ID": 42, "Hossz": 150, "Magasság": 80 },
    { "ID": 43, "Hossz": 400, "Magasság": 180 },
    { "ID": 44, "Hossz": 200, "Magasság": 80 },
    { "ID": 45, "Hossz": 300, "Magasság": 140 },
    { "ID": 46, "Hossz": 220, "Magasság": 100 },
    { "ID": 47, "Hossz": 160, "Magasság": 90 },
    { "ID": 48, "Hossz": 150, "Magasság": 70 },
    { "ID": 49, "Hossz": 180, "Magasság": 120 },
    { "ID": 50, "Hossz": 200, "Magasság": 100 }
],
terulet = [
    {"ID": 1, "Helyszín_ID": 1, "Típus": "Erdőterület", "VédelmiSzint": "Védett"},
    {"ID": 2, "Helyszín_ID": 2, "Típus": "Erdőterület", "VédelmiSzint": "Védett"},
    {"ID": 3, "Helyszín_ID": 3, "Típus": "Hegyi terület", "VédelmiSzint": "Védett"},
    {"ID": 4, "Helyszín_ID": 4, "Típus": "Óceán", "VédelmiSzint": "Védett"},
    {"ID": 5, "Helyszín_ID": 5, "Típus": "Erdő- és mocsáterület", "VédelmiSzint": "Védett"},
    {"ID": 6, "Helyszín_ID": 6, "Típus": "Mangróveterület", "VédelmiSzint": "Védett"},
    {"ID": 7, "Helyszín_ID": 7, "Típus": "Tengeri terület", "VédelmiSzint": "Védett"},
    {"ID": 8, "Helyszín_ID": 8, "Típus": "Esőerdő", "VédelmiSzint": "Védett"},
    {"ID": 9, "Helyszín_ID": 9, "Típus": "Szavanna", "VédelmiSzint": "Védett"},
    {"ID": 10, "Helyszín_ID": 10, "Típus": "Erdőterület", "VédelmiSzint": "Védett"},
    {"ID": 11, "Helyszín_ID": 11, "Típus": "Esőerdő", "VédelmiSzint": "Védett"},
    {"ID": 12, "Helyszín_ID": 12, "Típus": "Jégterület", "VédelmiSzint": "Védett"},
    {"ID": 13, "Helyszín_ID": 13, "Típus": "Cserjés terület", "VédelmiSzint": "Védett"},
    {"ID": 14, "Helyszín_ID": 14, "Típus": "Sivatag", "VédelmiSzint": "Védett"},
    {"ID": 15, "Helyszín_ID": 15, "Típus": "Tundra", "VédelmiSzint": "Védett"},
    {"ID": 16, "Helyszín_ID": 16, "Típus": "Esőerdő", "VédelmiSzint": "Védett"},
    {"ID": 17, "Helyszín_ID": 17, "Típus": "Sivatag", "VédelmiSzint": "Védett"},
    {"ID": 18, "Helyszín_ID": 18, "Típus": "Cserjés terület", "VédelmiSzint": "Védett"},
    {"ID": 19, "Helyszín_ID": 19, "Típus": "Tengeri terület", "VédelmiSzint": "Védett"},
    {"ID": 20, "Helyszín_ID": 20, "Típus": "Felhőerdő", "VédelmiSzint": "Védett"},
    {"ID": 21, "Helyszín_ID": 21, "Típus": "Örökzöld erdő", "VédelmiSzint": "Védett"},
    {"ID": 22, "Helyszín_ID": 22, "Típus": "Erdő", "VédelmiSzint": "Védett"},
    {"ID": 23, "Helyszín_ID": 23, "Típus": "Tüskés erdő", "VédelmiSzint": "Védett"},
    {"ID": 24, "Helyszín_ID": 24, "Típus": "Felföld", "VédelmiSzint": "Védett"},
    {"ID": 25, "Helyszín_ID": 25, "Típus": "Sztyeppe", "VédelmiSzint": "Védett"},
    {"ID": 26, "Helyszín_ID": 26, "Típus": "Sivatag", "VédelmiSzint": "Védett"},
    {"ID": 27, "Helyszín_ID": 27, "Típus": "Tundra", "VédelmiSzint": "Védett"},
    {"ID": 28, "Helyszín_ID": 28, "Típus": "Vegyes erdő", "VédelmiSzint": "Védett"},
    {"ID": 29, "Helyszín_ID": 29, "Típus": "Mangróvmocsár", "VédelmiSzint": "Védett"},
    {"ID": 30, "Helyszín_ID": 30, "Típus": "Lombhullató erdő", "VédelmiSzint": "Védett"},
    {"ID": 31, "Helyszín_ID": 31, "Típus": "Tőzegmocsár", "VédelmiSzint": "Védett"},
    {"ID": 32, "Helyszín_ID": 32, "Típus": "Trópusi erdő", "VédelmiSzint": "Védett"},
    {"ID": 33, "Helyszín_ID": 33, "Típus": "Dombvidéki erdő", "VédelmiSzint": "Védett"},
    {"ID": 34, "Helyszín_ID": 34, "Típus": "Fűtáj", "VédelmiSzint": "Védett"},
    {"ID": 35, "Helyszín_ID": 35, "Típus": "Sivatag", "VédelmiSzint": "Védett"},
    {"ID": 36, "Helyszín_ID": 36, "Típus": "Alacsony fekvésű erdő", "VédelmiSzint": "Védett"},
    {"ID": 37, "Helyszín_ID": 37, "Típus": "Szavanna", "VédelmiSzint": "Védett"},
    {"ID": 38, "Helyszín_ID": 38, "Típus": "Erdőterület", "VédelmiSzint": "Védett"},
    {"ID": 39, "Helyszín_ID": 39, "Típus": "Mocsarak", "VédelmiSzint": "Védett"},
    {"ID": 40, "Helyszín_ID": 40, "Típus": "Mérsékelt hegyek", "VédelmiSzint": "Védett"},
    {"ID": 41, "Helyszín_ID": 41, "Típus": "Hegység", "VédelmiSzint": "Védett"},
    {"ID": 42, "Helyszín_ID": 42, "Típus": "Sztyeppe és erdő", "VédelmiSzint": "Védett"},
    {"ID": 43, "Helyszín_ID": 43, "Típus": "Gleccser terület", "VédelmiSzint": "Védett"},
    {"ID": 44, "Helyszín_ID": 44, "Típus": "Trópusi szigetek", "VédelmiSzint": "Védett"},
    {"ID": 45, "Helyszín_ID": 45, "Típus": "Hegység", "VédelmiSzint": "Védett"},
    {"ID": 46, "Helyszín_ID": 46, "Típus": "Szubtrópusi erdő", "VédelmiSzint": "Védett"},
    {"ID": 47, "Helyszín_ID": 47, "Típus": "Folyómedence", "VédelmiSzint": "Védett"},
    {"ID": 48, "Helyszín_ID": 48, "Típus": "Mangróvmocsár", "VédelmiSzint": "Védett"},
    {"ID": 49, "Helyszín_ID": 49, "Típus": "Szigetvilág", "VédelmiSzint": "Védett"},
    {"ID": 50, "Helyszín_ID": 50, "Típus": "Sztyeppe", "VédelmiSzint": "Védett"}
]



};